// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type UserLoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserLoginResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Token   string `json:"token"`
}

type UserRegisterRequest struct {
	UserName        string `json:"username"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirm_password"` // 修正大小写规范
	Email           string `json:"email"`
}

type UserRegisterResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	UserId  string `json:"user_id"` // 修正命名规范：user_id -> UserId（go习惯）
}
