// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: Login_Register.proto

package server

import (
	"context"

	"Register_Login_Rpc/User"
	"Register_Login_Rpc/internal/logic"
	"Register_Login_Rpc/internal/svc"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	User.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) Register(ctx context.Context, in *User.RegisterRequest) (*User.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServiceServer) Login(ctx context.Context, in *User.LoginRequest) (*User.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
